# Generated by Django 2.2.5 on 2019-10-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hours', models.IntegerField(default=0, help_text='Enter a project hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
