# Generated by Django 2.1 on 2019-10-04 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours',
            name='responsible',
        ),
        migrations.AddField(
            model_name='hours',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
