# Generated by Django 2.2.5 on 2019-10-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, help_text='Enter a project value', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
