# Generated by Django 2.1 on 2019-10-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0002_auto_20191004_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='values',
            old_name='responsible',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='values',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
