# Generated by Django 2.1 on 2019-10-23 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandCode', models.IntegerField(help_text='Enter a demand code')),
                ('description', models.CharField(help_text='Enter project description', max_length=60)),
                ('value', models.DecimalField(decimal_places=2, help_text='Enter a project value', max_digits=20)),
                ('hoursAp', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('1', 'Planning'), ('2', 'Execution'), ('3', 'Tests'), ('4', 'Go Live'), ('5', 'Finished')], default='1', help_text='Project Status', max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
