# Generated by Django 2.2.5 on 2019-10-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('demandCode', models.IntegerField(help_text='Enter a demand code')),
                ('description', models.CharField(help_text='Enter project description', max_length=60)),
                ('value', models.DecimalField(decimal_places=2, help_text='Enter a project value', max_digits=20)),
                ('hoursAp', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('1', 'Planning'), ('2', 'Execution'), ('3', 'Tests'), ('4', 'Go Live'), ('5', 'Finished')], default='1', help_text='Project Status', max_length=2)),
            ],
        ),
    ]
