# Generated by Django 2.1 on 2019-10-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191004_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='responsible',
            new_name='user',
        ),
    ]
